class AddShortNameToTradingCountries < ActiveRecord::Migration
  def self.up
    add_column :trading_countries, :short_name, :string

    #short names provided by Kelly Malsch, file saved in PivotalTracker

    #These aren't working, even though the characters are accepted in the load_trading_countries migration
    #execute "UPDATE trading_countries SET short_name = 'Réunion' WHERE iso_country_code = 'RE';"
    #execute "UPDATE trading_countries SET short_name = 'Côte d''Ivoire' WHERE iso_country_code = 'CI';"
    #execute "UPDATE trading_countries SET short_name = 'São Tomé & Principe' WHERE iso_country_code = 'ST';"

    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'RE';"
    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'CI';"
    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'ST';"

    #these aren't specified in Kelly's spreadsheet
    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'CP';"
    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'BL';"
    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'MF';"
    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'EY';"
    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'FX';"
    execute "UPDATE trading_countries SET short_name = name WHERE iso_country_code = 'AX';"


    execute "UPDATE trading_countries SET short_name = 'Andorra' WHERE iso_country_code = 'AD';"
    execute "UPDATE trading_countries SET short_name = 'U.A.E.' WHERE iso_country_code = 'AE';"
    execute "UPDATE trading_countries SET short_name = 'Afghanistan' WHERE iso_country_code = 'AF';"
    execute "UPDATE trading_countries SET short_name = 'Antigua & Barbuda' WHERE iso_country_code = 'AG';"
    execute "UPDATE trading_countries SET short_name = 'Anguilla' WHERE iso_country_code = 'AI';"
    execute "UPDATE trading_countries SET short_name = 'Albania' WHERE iso_country_code = 'AL';"
    execute "UPDATE trading_countries SET short_name = 'Armenia' WHERE iso_country_code = 'AM';"
    execute "UPDATE trading_countries SET short_name = 'Netherlands Antilles' WHERE iso_country_code = 'AN';"
    execute "UPDATE trading_countries SET short_name = 'Angola' WHERE iso_country_code = 'AO';"
    execute "UPDATE trading_countries SET short_name = 'Antarctica' WHERE iso_country_code = 'AQ';"
    execute "UPDATE trading_countries SET short_name = 'Argentina' WHERE iso_country_code = 'AR';"
    execute "UPDATE trading_countries SET short_name = 'American Samoa' WHERE iso_country_code = 'AS';"
    execute "UPDATE trading_countries SET short_name = 'Austria' WHERE iso_country_code = 'AT';"
    execute "UPDATE trading_countries SET short_name = 'Australia' WHERE iso_country_code = 'AU';"
    execute "UPDATE trading_countries SET short_name = 'Aruba' WHERE iso_country_code = 'AW';"
    execute "UPDATE trading_countries SET short_name = 'Azerbaijan' WHERE iso_country_code = 'AZ';"
    execute "UPDATE trading_countries SET short_name = 'Bosnia & Herzegovina' WHERE iso_country_code = 'BA';"
    execute "UPDATE trading_countries SET short_name = 'Barbados' WHERE iso_country_code = 'BB';"
    execute "UPDATE trading_countries SET short_name = 'Bangladesh' WHERE iso_country_code = 'BD';"
    execute "UPDATE trading_countries SET short_name = 'Belgium' WHERE iso_country_code = 'BE';"
    execute "UPDATE trading_countries SET short_name = 'Burkina Faso' WHERE iso_country_code = 'BF';"
    execute "UPDATE trading_countries SET short_name = 'Bulgaria' WHERE iso_country_code = 'BG';"
    execute "UPDATE trading_countries SET short_name = 'Bahrain' WHERE iso_country_code = 'BH';"
    execute "UPDATE trading_countries SET short_name = 'Burundi' WHERE iso_country_code = 'BI';"
    execute "UPDATE trading_countries SET short_name = 'Benin' WHERE iso_country_code = 'BJ';"
    execute "UPDATE trading_countries SET short_name = 'Bermuda' WHERE iso_country_code = 'BM';"
    execute "UPDATE trading_countries SET short_name = 'Brunei' WHERE iso_country_code = 'BN';"
    execute "UPDATE trading_countries SET short_name = 'Bolivia' WHERE iso_country_code = 'BO';"
    execute "UPDATE trading_countries SET short_name = 'Brazil' WHERE iso_country_code = 'BR';"
    execute "UPDATE trading_countries SET short_name = 'Bahamas' WHERE iso_country_code = 'BS';"
    execute "UPDATE trading_countries SET short_name = 'Bhutan' WHERE iso_country_code = 'BT';"
    execute "UPDATE trading_countries SET short_name = 'Bouvet Island' WHERE iso_country_code = 'BV';"
    execute "UPDATE trading_countries SET short_name = 'Botswana' WHERE iso_country_code = 'BW';"
    execute "UPDATE trading_countries SET short_name = 'Belarus' WHERE iso_country_code = 'BY';"
    execute "UPDATE trading_countries SET short_name = 'Belize' WHERE iso_country_code = 'BZ';"
    execute "UPDATE trading_countries SET short_name = 'Canada' WHERE iso_country_code = 'CA';"
    execute "UPDATE trading_countries SET short_name = 'Cocos Islands' WHERE iso_country_code = 'CC';"
    execute "UPDATE trading_countries SET short_name = 'C. African Rep.' WHERE iso_country_code = 'CF';"
    execute "UPDATE trading_countries SET short_name = 'Congo' WHERE iso_country_code = 'CG';"
    execute "UPDATE trading_countries SET short_name = 'Switzerland' WHERE iso_country_code = 'CH';"
    #execute "UPDATE trading_countries SET short_name = 'Côte d''Ivoire' WHERE iso_country_code = 'CI';"
    execute "UPDATE trading_countries SET short_name = 'D.R. Congo' WHERE iso_country_code = 'CD';"
    execute "UPDATE trading_countries SET short_name = 'Cook Islands' WHERE iso_country_code = 'CK';"
    execute "UPDATE trading_countries SET short_name = 'Chile' WHERE iso_country_code = 'CL';"
    execute "UPDATE trading_countries SET short_name = 'Cameroon' WHERE iso_country_code = 'CM';"
    execute "UPDATE trading_countries SET short_name = 'China' WHERE iso_country_code = 'CN';"
    execute "UPDATE trading_countries SET short_name = 'Colombia' WHERE iso_country_code = 'CO';"
    execute "UPDATE trading_countries SET short_name = 'Costa Rica' WHERE iso_country_code = 'CR';"
    execute "UPDATE trading_countries SET short_name = 'Serbia & Montenegro' WHERE iso_country_code = 'CS';"
    execute "UPDATE trading_countries SET short_name = 'Cuba' WHERE iso_country_code = 'CU';"
    execute "UPDATE trading_countries SET short_name = 'Cape Verde' WHERE iso_country_code = 'CV';"
    execute "UPDATE trading_countries SET short_name = 'Christmas Island' WHERE iso_country_code = 'CX';"
    execute "UPDATE trading_countries SET short_name = 'Cyprus' WHERE iso_country_code = 'CY';"
    execute "UPDATE trading_countries SET short_name = 'Czech Republic' WHERE iso_country_code = 'CZ';"
    execute "UPDATE trading_countries SET short_name = 'Germany' WHERE iso_country_code = 'DE';"
    execute "UPDATE trading_countries SET short_name = 'Djibouti' WHERE iso_country_code = 'DJ';"
    execute "UPDATE trading_countries SET short_name = 'Denmark' WHERE iso_country_code = 'DK';"
    execute "UPDATE trading_countries SET short_name = 'Dominica' WHERE iso_country_code = 'DM';"
    execute "UPDATE trading_countries SET short_name = 'Dominican Republic' WHERE iso_country_code = 'DO';"
    execute "UPDATE trading_countries SET short_name = 'Algeria' WHERE iso_country_code = 'DZ';"
    execute "UPDATE trading_countries SET short_name = 'Ecuador' WHERE iso_country_code = 'EC';"
    execute "UPDATE trading_countries SET short_name = 'Estonia' WHERE iso_country_code = 'EE';"
    execute "UPDATE trading_countries SET short_name = 'Egypt' WHERE iso_country_code = 'EG';"
    execute "UPDATE trading_countries SET short_name = 'Western Sahara' WHERE iso_country_code = 'EH';"
    execute "UPDATE trading_countries SET short_name = 'Spain' WHERE iso_country_code = 'ES';"
    execute "UPDATE trading_countries SET short_name = 'Ethiopia' WHERE iso_country_code = 'ET';"
    execute "UPDATE trading_countries SET short_name = 'Finland' WHERE iso_country_code = 'FI';"
    execute "UPDATE trading_countries SET short_name = 'Fiji' WHERE iso_country_code = 'FJ';"
    execute "UPDATE trading_countries SET short_name = 'Falkland Islands' WHERE iso_country_code = 'FK';"
    execute "UPDATE trading_countries SET short_name = 'Eritrea' WHERE iso_country_code = 'ER';"
    execute "UPDATE trading_countries SET short_name = 'Micronesia' WHERE iso_country_code = 'FM';"
    execute "UPDATE trading_countries SET short_name = 'Faeroe Islands' WHERE iso_country_code = 'FO';"
    execute "UPDATE trading_countries SET short_name = 'France' WHERE iso_country_code = 'FR';"
    execute "UPDATE trading_countries SET short_name = 'Gabon' WHERE iso_country_code = 'GA';"
    execute "UPDATE trading_countries SET short_name = 'United Kingdom' WHERE iso_country_code = 'GB';"
    execute "UPDATE trading_countries SET short_name = 'Grenada' WHERE iso_country_code = 'GD';"
    execute "UPDATE trading_countries SET short_name = 'Georgia' WHERE iso_country_code = 'GE';"
    execute "UPDATE trading_countries SET short_name = 'French Guiana' WHERE iso_country_code = 'GF';"
    execute "UPDATE trading_countries SET short_name = 'Ghana' WHERE iso_country_code = 'GH';"
    execute "UPDATE trading_countries SET short_name = 'Gibraltar' WHERE iso_country_code = 'GI';"
    execute "UPDATE trading_countries SET short_name = 'Greenland' WHERE iso_country_code = 'GL';"
    execute "UPDATE trading_countries SET short_name = 'Gambia' WHERE iso_country_code = 'GM';"
    execute "UPDATE trading_countries SET short_name = 'Guinea' WHERE iso_country_code = 'GN';"
    execute "UPDATE trading_countries SET short_name = 'Guadeloupe' WHERE iso_country_code = 'GP';"
    execute "UPDATE trading_countries SET short_name = 'Equatorial Guinea' WHERE iso_country_code = 'GQ';"
    execute "UPDATE trading_countries SET short_name = 'Greece' WHERE iso_country_code = 'GR';"
    execute "UPDATE trading_countries SET short_name = 'Guatemala' WHERE iso_country_code = 'GT';"
    execute "UPDATE trading_countries SET short_name = 'Guam' WHERE iso_country_code = 'GU';"
    execute "UPDATE trading_countries SET short_name = 'Guinea Bissau' WHERE iso_country_code = 'GW';"
    execute "UPDATE trading_countries SET short_name = 'Guyana' WHERE iso_country_code = 'GY';"
    execute "UPDATE trading_countries SET short_name = 'Hong Kong, SAR' WHERE iso_country_code = 'HK';"
    execute "UPDATE trading_countries SET short_name = 'South Georgia' WHERE iso_country_code = 'GS';"
    execute "UPDATE trading_countries SET short_name = 'Heard Island' WHERE iso_country_code = 'HM';"
    execute "UPDATE trading_countries SET short_name = 'Honduras' WHERE iso_country_code = 'HN';"
    execute "UPDATE trading_countries SET short_name = 'Croatia' WHERE iso_country_code = 'HR';"
    execute "UPDATE trading_countries SET short_name = 'Haiti' WHERE iso_country_code = 'HT';"
    execute "UPDATE trading_countries SET short_name = 'Hungary' WHERE iso_country_code = 'HU';"
    execute "UPDATE trading_countries SET short_name = 'Indonesia' WHERE iso_country_code = 'ID';"
    execute "UPDATE trading_countries SET short_name = 'Ireland' WHERE iso_country_code = 'IE';"
    execute "UPDATE trading_countries SET short_name = 'Israel' WHERE iso_country_code = 'IL';"
    execute "UPDATE trading_countries SET short_name = 'India' WHERE iso_country_code = 'IN';"
    execute "UPDATE trading_countries SET short_name = 'BIOT' WHERE iso_country_code = 'IO';"
    execute "UPDATE trading_countries SET short_name = 'Iraq' WHERE iso_country_code = 'IQ';"
    execute "UPDATE trading_countries SET short_name = 'Iran' WHERE iso_country_code = 'IR';"
    execute "UPDATE trading_countries SET short_name = 'Iceland' WHERE iso_country_code = 'IS';"
    execute "UPDATE trading_countries SET short_name = 'Italy' WHERE iso_country_code = 'IT';"
    execute "UPDATE trading_countries SET short_name = 'Jamaica' WHERE iso_country_code = 'JM';"
    execute "UPDATE trading_countries SET short_name = 'Jordan' WHERE iso_country_code = 'JO';"
    execute "UPDATE trading_countries SET short_name = 'Japan' WHERE iso_country_code = 'JP';"
    execute "UPDATE trading_countries SET short_name = 'Kenya' WHERE iso_country_code = 'KE';"
    execute "UPDATE trading_countries SET short_name = 'Kyrgyzstan' WHERE iso_country_code = 'KG';"
    execute "UPDATE trading_countries SET short_name = 'Cambodia' WHERE iso_country_code = 'KH';"
    execute "UPDATE trading_countries SET short_name = 'Kiribati' WHERE iso_country_code = 'KI';"
    execute "UPDATE trading_countries SET short_name = 'Comoros' WHERE iso_country_code = 'KM';"
    execute "UPDATE trading_countries SET short_name = 'St Kitts & Nevis' WHERE iso_country_code = 'KN';"
    execute "UPDATE trading_countries SET short_name = 'North Korea' WHERE iso_country_code = 'KP';"
    execute "UPDATE trading_countries SET short_name = 'South Korea' WHERE iso_country_code = 'KR';"
    execute "UPDATE trading_countries SET short_name = 'Kuwait' WHERE iso_country_code = 'KW';"
    execute "UPDATE trading_countries SET short_name = 'Cayman Islands' WHERE iso_country_code = 'KY';"
    execute "UPDATE trading_countries SET short_name = 'Kazakhstan' WHERE iso_country_code = 'KZ';"
    execute "UPDATE trading_countries SET short_name = 'Lao PDR' WHERE iso_country_code = 'LA';"
    execute "UPDATE trading_countries SET short_name = 'Lebanon' WHERE iso_country_code = 'LB';"
    execute "UPDATE trading_countries SET short_name = 'St. Lucia' WHERE iso_country_code = 'LC';"
    execute "UPDATE trading_countries SET short_name = 'Liechtenstein' WHERE iso_country_code = 'LI';"
    execute "UPDATE trading_countries SET short_name = 'Sri Lanka' WHERE iso_country_code = 'LK';"
    execute "UPDATE trading_countries SET short_name = 'Liberia' WHERE iso_country_code = 'LR';"
    execute "UPDATE trading_countries SET short_name = 'Lesotho' WHERE iso_country_code = 'LS';"
    execute "UPDATE trading_countries SET short_name = 'Lithuania' WHERE iso_country_code = 'LT';"
    execute "UPDATE trading_countries SET short_name = 'Luxembourg' WHERE iso_country_code = 'LU';"
    execute "UPDATE trading_countries SET short_name = 'Latvia' WHERE iso_country_code = 'LV';"
    execute "UPDATE trading_countries SET short_name = 'Libya' WHERE iso_country_code = 'LY';"
    execute "UPDATE trading_countries SET short_name = 'Morocco' WHERE iso_country_code = 'MA';"
    execute "UPDATE trading_countries SET short_name = 'Monaco' WHERE iso_country_code = 'MC';"
    execute "UPDATE trading_countries SET short_name = 'Moldova' WHERE iso_country_code = 'MD';"
    execute "UPDATE trading_countries SET short_name = 'Madagascar' WHERE iso_country_code = 'MG';"
    execute "UPDATE trading_countries SET short_name = 'Marshall Islands' WHERE iso_country_code = 'MH';"
    execute "UPDATE trading_countries SET short_name = 'Mali' WHERE iso_country_code = 'ML';"
    execute "UPDATE trading_countries SET short_name = 'Mongolia' WHERE iso_country_code = 'MN';"
    execute "UPDATE trading_countries SET short_name = 'Macao' WHERE iso_country_code = 'MO';"
    execute "UPDATE trading_countries SET short_name = 'N. Marianas' WHERE iso_country_code = 'MP';"
    execute "UPDATE trading_countries SET short_name = 'Martinique' WHERE iso_country_code = 'MQ';"
    execute "UPDATE trading_countries SET short_name = 'Myanmar' WHERE iso_country_code = 'MM';"
    execute "UPDATE trading_countries SET short_name = 'FYR Macedonia' WHERE iso_country_code = 'MK';"
    execute "UPDATE trading_countries SET short_name = 'Mauritania' WHERE iso_country_code = 'MR';"
    execute "UPDATE trading_countries SET short_name = 'Montserrat' WHERE iso_country_code = 'MS';"
    execute "UPDATE trading_countries SET short_name = 'Malta' WHERE iso_country_code = 'MT';"
    execute "UPDATE trading_countries SET short_name = 'Mauritius' WHERE iso_country_code = 'MU';"
    execute "UPDATE trading_countries SET short_name = 'Maldives' WHERE iso_country_code = 'MV';"
    execute "UPDATE trading_countries SET short_name = 'Malawi' WHERE iso_country_code = 'MW';"
    execute "UPDATE trading_countries SET short_name = 'Mexico' WHERE iso_country_code = 'MX';"
    execute "UPDATE trading_countries SET short_name = 'Malaysia' WHERE iso_country_code = 'MY';"
    execute "UPDATE trading_countries SET short_name = 'Mozambique' WHERE iso_country_code = 'MZ';"
    execute "UPDATE trading_countries SET short_name = 'Namibia' WHERE iso_country_code = 'NA';"
    execute "UPDATE trading_countries SET short_name = 'New Caledonia' WHERE iso_country_code = 'NC';"
    execute "UPDATE trading_countries SET short_name = 'Niger' WHERE iso_country_code = 'NE';"
    execute "UPDATE trading_countries SET short_name = 'Norfolk Island' WHERE iso_country_code = 'NF';"
    execute "UPDATE trading_countries SET short_name = 'Nigeria' WHERE iso_country_code = 'NG';"
    execute "UPDATE trading_countries SET short_name = 'Nicaragua' WHERE iso_country_code = 'NI';"
    execute "UPDATE trading_countries SET short_name = 'Netherlands' WHERE iso_country_code = 'NL';"
    execute "UPDATE trading_countries SET short_name = 'Norway' WHERE iso_country_code = 'NO';"
    execute "UPDATE trading_countries SET short_name = 'Nepal' WHERE iso_country_code = 'NP';"
    execute "UPDATE trading_countries SET short_name = 'Nauru' WHERE iso_country_code = 'NR';"
    execute "UPDATE trading_countries SET short_name = 'Niue' WHERE iso_country_code = 'NU';"
    execute "UPDATE trading_countries SET short_name = 'New Zealand' WHERE iso_country_code = 'NZ';"
    execute "UPDATE trading_countries SET short_name = 'Oman' WHERE iso_country_code = 'OM';"
    execute "UPDATE trading_countries SET short_name = 'Panama' WHERE iso_country_code = 'PA';"
    execute "UPDATE trading_countries SET short_name = 'Peru' WHERE iso_country_code = 'PE';"
    execute "UPDATE trading_countries SET short_name = 'French Polynesia' WHERE iso_country_code = 'PF';"
    execute "UPDATE trading_countries SET short_name = 'Papua New Guinea' WHERE iso_country_code = 'PG';"
    execute "UPDATE trading_countries SET short_name = 'Philippines' WHERE iso_country_code = 'PH';"
    execute "UPDATE trading_countries SET short_name = 'Pakistan' WHERE iso_country_code = 'PK';"
    execute "UPDATE trading_countries SET short_name = 'Poland' WHERE iso_country_code = 'PL';"
    execute "UPDATE trading_countries SET short_name = 'St. Pierre & Miquelon' WHERE iso_country_code = 'PM';"
    execute "UPDATE trading_countries SET short_name = 'Pitcairn' WHERE iso_country_code = 'PN';"
    execute "UPDATE trading_countries SET short_name = 'Puerto Rico' WHERE iso_country_code = 'PR';"
    execute "UPDATE trading_countries SET short_name = 'Portugal' WHERE iso_country_code = 'PT';"
    execute "UPDATE trading_countries SET short_name = 'Occupied Palestine' WHERE iso_country_code = 'PS';"
    execute "UPDATE trading_countries SET short_name = 'Palau' WHERE iso_country_code = 'PW';"
    execute "UPDATE trading_countries SET short_name = 'Paraguay' WHERE iso_country_code = 'PY';"
    execute "UPDATE trading_countries SET short_name = 'Qatar' WHERE iso_country_code = 'QA';"
    #execute "UPDATE trading_countries SET short_name = 'Réunion' WHERE iso_country_code = 'RE';"
    execute "UPDATE trading_countries SET short_name = 'Romania' WHERE iso_country_code = 'RO';"
    execute "UPDATE trading_countries SET short_name = 'Russia' WHERE iso_country_code = 'RU';"
    execute "UPDATE trading_countries SET short_name = 'Rwanda' WHERE iso_country_code = 'RW';"
    execute "UPDATE trading_countries SET short_name = 'Saudi Arabia' WHERE iso_country_code = 'SA';"
    execute "UPDATE trading_countries SET short_name = 'Solomon Islands' WHERE iso_country_code = 'SB';"
    execute "UPDATE trading_countries SET short_name = 'Seychelles' WHERE iso_country_code = 'SC';"
    execute "UPDATE trading_countries SET short_name = 'Sudan' WHERE iso_country_code = 'SD';"
    execute "UPDATE trading_countries SET short_name = 'Sweden' WHERE iso_country_code = 'SE';"
    execute "UPDATE trading_countries SET short_name = 'Singapore' WHERE iso_country_code = 'SG';"
    execute "UPDATE trading_countries SET short_name = 'Saint Helena' WHERE iso_country_code = 'SH';"
    execute "UPDATE trading_countries SET short_name = 'Slovenia' WHERE iso_country_code = 'SI';"
    execute "UPDATE trading_countries SET short_name = 'Svalbard' WHERE iso_country_code = 'SJ';"
    execute "UPDATE trading_countries SET short_name = 'Slovakia' WHERE iso_country_code = 'SK';"
    execute "UPDATE trading_countries SET short_name = 'Sierra Leone' WHERE iso_country_code = 'SL';"
    execute "UPDATE trading_countries SET short_name = 'San Marino' WHERE iso_country_code = 'SM';"
    execute "UPDATE trading_countries SET short_name = 'Senegal' WHERE iso_country_code = 'SN';"
    execute "UPDATE trading_countries SET short_name = 'Somalia' WHERE iso_country_code = 'SO';"
    execute "UPDATE trading_countries SET short_name = 'Suriname' WHERE iso_country_code = 'SR';"
    #execute "UPDATE trading_countries SET short_name = 'São Tomé & Principe' WHERE iso_country_code = 'ST';"
    execute "UPDATE trading_countries SET short_name = 'former USSR' WHERE iso_country_code = 'SU';"
    execute "UPDATE trading_countries SET short_name = 'El Salvador' WHERE iso_country_code = 'SV';"
    execute "UPDATE trading_countries SET short_name = 'Syria' WHERE iso_country_code = 'SY';"
    execute "UPDATE trading_countries SET short_name = 'Swaziland' WHERE iso_country_code = 'SZ';"
    execute "UPDATE trading_countries SET short_name = 'Turks & Caicos' WHERE iso_country_code = 'TC';"
    execute "UPDATE trading_countries SET short_name = 'Chad' WHERE iso_country_code = 'TD';"
    execute "UPDATE trading_countries SET short_name = 'French S. Terr.' WHERE iso_country_code = 'TF';"
    execute "UPDATE trading_countries SET short_name = 'Togo' WHERE iso_country_code = 'TG';"
    execute "UPDATE trading_countries SET short_name = 'Thailand' WHERE iso_country_code = 'TH';"
    execute "UPDATE trading_countries SET short_name = 'Tokelau' WHERE iso_country_code = 'TK';"
    execute "UPDATE trading_countries SET short_name = 'Turkmenistan' WHERE iso_country_code = 'TM';"
    execute "UPDATE trading_countries SET short_name = 'Tunisia' WHERE iso_country_code = 'TN';"
    execute "UPDATE trading_countries SET short_name = 'Tajikistan' WHERE iso_country_code = 'TJ';"
    execute "UPDATE trading_countries SET short_name = 'Tonga' WHERE iso_country_code = 'TO';"
    execute "UPDATE trading_countries SET short_name = 'Timor-Leste' WHERE iso_country_code = 'TL';"
    execute "UPDATE trading_countries SET short_name = 'Turkey' WHERE iso_country_code = 'TR';"
    execute "UPDATE trading_countries SET short_name = 'Trinidad & Tobago' WHERE iso_country_code = 'TT';"
    execute "UPDATE trading_countries SET short_name = 'Tuvalu' WHERE iso_country_code = 'TV';"
    execute "UPDATE trading_countries SET short_name = 'Taiwan' WHERE iso_country_code = 'TW';"
    execute "UPDATE trading_countries SET short_name = 'Tanzania' WHERE iso_country_code = 'TZ';"
    execute "UPDATE trading_countries SET short_name = 'Ukraine' WHERE iso_country_code = 'UA';"
    execute "UPDATE trading_countries SET short_name = 'Uganda' WHERE iso_country_code = 'UG';"
    execute "UPDATE trading_countries SET short_name = 'US Minor Islands' WHERE iso_country_code = 'UM';"
    execute "UPDATE trading_countries SET short_name = 'USA' WHERE iso_country_code = 'US';"
    execute "UPDATE trading_countries SET short_name = 'Uruguay' WHERE iso_country_code = 'UY';"
    execute "UPDATE trading_countries SET short_name = 'Uzbekistan' WHERE iso_country_code = 'UZ';"
    execute "UPDATE trading_countries SET short_name = 'Holy See' WHERE iso_country_code = 'VA';"
    execute "UPDATE trading_countries SET short_name = 'St Vincent' WHERE iso_country_code = 'VC';"
    execute "UPDATE trading_countries SET short_name = 'Venezuela' WHERE iso_country_code = 'VE';"
    execute "UPDATE trading_countries SET short_name = 'British Virgin Is.' WHERE iso_country_code = 'VG';"
    execute "UPDATE trading_countries SET short_name = 'US Virgin Is.' WHERE iso_country_code = 'VI';"
    execute "UPDATE trading_countries SET short_name = 'Viet Nam' WHERE iso_country_code = 'VN';"
    execute "UPDATE trading_countries SET short_name = 'Vanuatu' WHERE iso_country_code = 'VU';"
    execute "UPDATE trading_countries SET short_name = 'Wallis & Futuna Is.' WHERE iso_country_code = 'WF';"
    execute "UPDATE trading_countries SET short_name = 'Samoa' WHERE iso_country_code = 'WS';"
    execute "UPDATE trading_countries SET short_name = 'Caribbean' WHERE iso_country_code = 'XC';"
    execute "UPDATE trading_countries SET short_name = 'Europe' WHERE iso_country_code = 'XE';"
    execute "UPDATE trading_countries SET short_name = 'Africa' WHERE iso_country_code = 'XF';"
    execute "UPDATE trading_countries SET short_name = 'South America' WHERE iso_country_code = 'XM';"
    execute "UPDATE trading_countries SET short_name = 'Asia' WHERE iso_country_code = 'XS';"
    execute "UPDATE trading_countries SET short_name = 'Various' WHERE iso_country_code = 'XV';"
    execute "UPDATE trading_countries SET short_name = 'French Antilles' WHERE iso_country_code = 'XA';"
    execute "UPDATE trading_countries SET short_name = 'Unknown' WHERE iso_country_code = 'XX';"
    execute "UPDATE trading_countries SET short_name = 'former Democratic Yemen' WHERE iso_country_code = 'YD';"
    execute "UPDATE trading_countries SET short_name = 'Yemen' WHERE iso_country_code = 'YE';"
    execute "UPDATE trading_countries SET short_name = 'Yugoslavia' WHERE iso_country_code = 'YU';"
    execute "UPDATE trading_countries SET short_name = 'South Africa' WHERE iso_country_code = 'ZA';"
    execute "UPDATE trading_countries SET short_name = 'Zambia' WHERE iso_country_code = 'ZM';"
    execute "UPDATE trading_countries SET short_name = 'Mayotte' WHERE iso_country_code = 'YT';"
    execute "UPDATE trading_countries SET short_name = 'Zimbabwe' WHERE iso_country_code = 'ZW';"
    execute "UPDATE trading_countries SET short_name = 'The Sea' WHERE iso_country_code = 'ZZ';"
    execute "UPDATE trading_countries SET short_name = 'former Czechoslovakia' WHERE iso_country_code = 'ZC';"
    execute "UPDATE trading_countries SET short_name = 'Guernsey' WHERE iso_country_code = 'GG';"
    execute "UPDATE trading_countries SET short_name = 'Jersey' WHERE iso_country_code = 'JE';"
    execute "UPDATE trading_countries SET short_name = 'Isle of Man' WHERE iso_country_code = 'IM';"
    execute "UPDATE trading_countries SET short_name = 'Serbia' WHERE iso_country_code = 'RS';"
    execute "UPDATE trading_countries SET short_name = 'Montenegro' WHERE iso_country_code = 'ME';"
    execute "UPDATE trading_countries SET short_name = 'Kosovo (disputed)' WHERE iso_country_code = 'KX';"

  end

  def self.down
    remove_column :trading_countries, :short_name
  end
end
