class LoadTradingCountries < ActiveRecord::Migration
  def self.up
    down

    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Switzerland' , 'CH' ,1975,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Chile' , 'CL' ,1975,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Cyprus' , 'CY' ,1975,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Ecuador' , 'EC' ,1975,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Nigeria' , 'NG' ,1975,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Sweden' , 'SE' ,1975,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Tunisia' , 'TN' ,1975,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('United States of America' , 'US' ,1975,5);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Uruguay' , 'UY' ,1975,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Canada' , 'CA' ,1975,5);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Mauritius' , 'MU' ,1975,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Nepal' , 'NP' ,1975,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Peru' , 'PE' ,1975,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Costa Rica' , 'CR' ,1975,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('South Africa' , 'ZA' ,1975,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Brazil' , 'BR' ,1975,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Madagascar' , 'MG' ,1975,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Niger' , 'NE' ,1975,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Morocco' , 'MA' ,1976,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Ghana' , 'GH' ,1976,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Papua New Guinea' , 'PG' ,1976,6);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Germany' , 'DE' ,1976,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Pakistan' , 'PK' ,1976,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Finland' , 'FI' ,1976,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Democratic Republic of the Congo' , 'CD' ,1976,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('India' , 'IN' ,1976,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Norway' , 'NO' ,1976,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Australia' , 'AU' ,1976,6);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('United Kingdom of Great Britain and Northern Ireland' , 'GB' ,1976,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Iran (Islamic Republic of)' , 'IR' ,1976,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Paraguay' , 'PY' ,1977,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Seychelles' , 'SC' ,1977,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Guyana' , 'GY' ,1977,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Denmark' , 'DK' ,1977,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Senegal' , 'SN' ,1977,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Nicaragua' , 'NI' ,1977,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Gambia' , 'GM' ,1977,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Malaysia' , 'MY' ,1978,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Venezuela (Bolivarian Republic of)' , 'VE' ,1978,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Botswana' , 'BW' ,1978,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Egypt' , 'EG' ,1978,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Monaco' , 'MC' ,1978,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('France' , 'FR' ,1978,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Panama' , 'PA' ,1978,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Togo' , 'TG' ,1979,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Kenya' , 'KE' ,1979,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Jordan' , 'JO' ,1979,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Indonesia' , 'ID' ,1979,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Sri Lanka' , 'LK' ,1979,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Bahamas' , 'BS' ,1979,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Bolivia (Plurinational State of)' , 'BO' ,1979,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Italy' , 'IT' ,1979,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Guatemala' , 'GT' ,1980,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Tanzania, United Republic of' , 'TZ' ,1980,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Liechtenstein' , 'LI' ,1980,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Israel' , 'IL' ,1980,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Japan' , 'JP' ,1980,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Central African Republic' , 'CF' ,1980,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Rwanda' , 'RW' ,1981,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Suriname' , 'SR' ,1981,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Zambia' , 'ZM' ,1981,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Portugal' , 'PT' ,1981,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Argentina' , 'AR' ,1981,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('China' , 'CN' ,1981,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Liberia' , 'LR' ,1981,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Mozambique' , 'MZ' ,1981,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Zimbabwe' , 'ZW' ,1981,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Cameroon' , 'CM' ,1981,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Belize' , 'BZ' ,1981,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Philippines' , 'PH' ,1981,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Colombia' , 'CO' ,1981,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Guinea' , 'GN' ,1981,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Bangladesh' , 'BD' ,1982,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Austria' , 'AT' ,1982,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Malawi' , 'MW' ,1982,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Sudan' , 'SD' ,1983,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Saint Lucia' , 'LC' ,1983,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Thailand' , 'TH' ,1983,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Congo, Republic of' , 'CG' ,1983,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Belgium' , 'BE' ,1984,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Algeria' , 'DZ' ,1984,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Luxembourg' , 'LU' ,1984,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Trinidad and Tobago' , 'TT' ,1984,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Benin' , 'BJ' ,1984,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Netherlands' , 'NL' ,1984,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Honduras' , 'HN' ,1985,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Hungary' , 'HU' ,1985,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Afghanistan' , 'AF' ,1986,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Somalia' , 'SO' ,1986,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Spain' , 'ES' ,1986,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Singapore' , 'SG' ,1987,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Dominican Republic' , 'DO' ,1987,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('El Salvador' , 'SV' ,1987,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Burundi' , 'BI' ,1988,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Saint Vincent and the Grenadines' , 'VC' ,1989,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Chad' , 'TD' ,1989,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Gabon' , 'GA' ,1989,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Ethiopia' , 'ET' ,1989,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Malta' , 'MT' ,1989,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('New Zealand' , 'NZ' ,1989,6);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Vanuatu' , 'VU' ,1989,6);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Burkina Faso' , 'BF' ,1990,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Poland' , 'PL' ,1990,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('United Arab Emirates' , 'AE' ,1990,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Cuba' , 'CU' ,1990,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Brunei Darussalam' , 'BN' ,1990,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Guinea-Bissau' , 'GW' ,1990,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Namibia' , 'NA' ,1991,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Bulgaria' , 'BG' ,1991,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Mexico' , 'MX' ,1991,5);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Uganda' , 'UG' ,1991,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Russian Federation' , 'RU' ,1992,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Djibouti' , 'DJ' ,1992,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Equatorial Guinea' , 'GQ' ,1992,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Estonia' , 'EE' ,1992,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Czech Republic' , 'CZ' ,1993,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Slovakia' , 'SK' ,1993,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Greece' , 'GR' ,1993,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Barbados' , 'BB' ,1993,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Republic of Korea' , 'KR' ,1993,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Viet Nam' , 'VN' ,1994,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Saint Kitts and Nevis' , 'KN' ,1994,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Mali' , 'ML' ,1994,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Romania' , 'RO' ,1994,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Eritrea' , 'ER' ,1995,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Sierra Leone' , 'SL' ,1995,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Côte d''Ivoire' , 'CI' ,1995,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Comoros' , 'KM' ,1995,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Dominica' , 'DM' ,1995,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Belarus' , 'BY' ,1995,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Mongolia' , 'MN' ,1996,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Saudi Arabia' , 'SA' ,1996,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Georgia' , 'GE' ,1996,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Turkey' , 'TR' ,1996,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Latvia' , 'LV' ,1997,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Swaziland' , 'SZ' ,1997,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Jamaica' , 'JM' ,1997,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Yemen' , 'YE' ,1997,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Myanmar' , 'MM' ,1997,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Cambodia' , 'KH' ,1997,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Antigua and Barbuda' , 'AG' ,1997,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Uzbekistan' , 'UZ' ,1997,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Fiji' , 'FJ' ,1997,6);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Mauritania' , 'MR' ,1998,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Azerbaijan' , 'AZ' ,1999,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Grenada' , 'GD' ,1999,3);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Ukraine' , 'UA' ,2000,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Iceland' , 'IS' ,2000,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Kazakhstan' , 'KZ' ,2000,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Slovenia' , 'SI' ,2000,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Croatia' , 'HR' ,2000,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('The former Yugoslav Republic of Macedonia' , 'MK' ,2000,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Republic of Moldova' , 'MD' ,2001,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Qatar' , 'QA' ,2001,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Sao Tome and Principe' , 'ST' ,2001,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Lithuania' , 'LT' ,2002,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Ireland' , 'IE' ,2002,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Kuwait' , 'KW' ,2002,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Bhutan' , 'BT' ,2002,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Libyan Arab Jamahiriya' , 'LY' ,2003,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Syrian Arab Republic' , 'SY' ,2003,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Albania' , 'AL' ,2003,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Lesotho' , 'LS' ,2003,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Lao People''s Democratic Republic' , 'LA' ,2004,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Palau' , 'PW' ,2004,6);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Samoa' , 'WS' ,2005,6);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('San Marino' , 'SM' ,2005,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Cape Verde' , 'CV' ,2005,1);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Montenegro' , 'ME' ,2006,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Serbia' , 'RS' ,2006,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Solomon Islands' , 'SB' ,2007,6);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Kyrgyzstan' , 'KG' ,2007,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Oman' , 'OM' ,2008,2);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Armenia' , 'AM' ,2009,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code,entry_date,cites_region_code) VALUES ('Bosnia and Herzegovina' , 'BA' ,2009,4);"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Andorra' , 'AD');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Anguilla' , 'AI');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Angola' , 'AO');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Bahrain' , 'BH');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Cook Islands' , 'CK');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Micronesia (Federated States of)' , 'FM');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Faroe Islands' , 'FO');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Haiti' , 'HT');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Iraq' , 'IQ');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Kiribati' , 'KI');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Democratic People''s Republic of Korea' , 'KP');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Lebanon' , 'LB');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Maldives' , 'MV');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Nauru' , 'NR');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Niue' , 'NU');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Turks and Caicos Islands' , 'TC');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Timor-Leste' , 'TL');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Turkmenistan' , 'TM');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Tonga' , 'TO');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Tuvalu' , 'TV');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Holy See' , 'VA');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Marshall Islands ' , 'MH');"
    execute "INSERT INTO trading_countries (name,iso_country_code) VALUES ('Tajikistan' , 'TJ');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Bermuda (GB)' , 'BM','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('British Indian Ocean Territory (GB)' , 'IO','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Cayman Islands (GB)' , 'KY','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Falkland Islands (GB)' , 'FK','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Guernsey (GB)' , 'GG','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Isle of Man (GB)' , 'IM','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Jersey (GB)' , 'JE','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('British Virgin Islands (GB)' , 'VG','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Gibraltar (GB)' , 'GI','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Montserrat (GB)' , 'MS','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Pitcairn Islands (GB)' , 'PN','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('St Helena & Dependencies (GB)' , 'SH','GB');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Greenland (DK)' , 'GL','DK');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Guadeloupe (FR)' , 'GP','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Martinique (FR)' , 'MQ','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('French Guiana (FR)' , 'GF','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Réunion (FR)' , 'RE','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Clipperton (FR)' , 'CP','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('French Polynesia (FR)' , 'PF','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Mayotte (FR)' , 'YT','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('New Caledonia (FR)' , 'NC','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('St. Bartelemy (FR)' , 'BL','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('St. Martin (FR)' , 'MF','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Southern and Antarctic Territories (FR)' , 'TF','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Wallis & Futuna Islands (FR)' , 'WF','FR');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('American Samoa (US)' , 'AS','US');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Guam (US)' , 'GU','US');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Northern Mariana Islands (US)' , 'MP','US');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Puerto Rico (US)' , 'PR','US');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Virgin Islands of the USA (US)' , 'VI','US');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Aruba (NL)' , 'AW','NL');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Netherlands Antilles (NL)' , 'AN','NL');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Hong Kong' , 'HK','CN');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Taiwan, Province of China' , 'TW','CN');"
    execute "INSERT INTO trading_countries (name,iso_country_code,dependency_of) VALUES ('Macao Special Administrative Region of China' , 'MO','CN');"

execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Antarctica', 'AQ',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Åland Islands', 'AX',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Bouvet Island', 'BV',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Cocos (Keeling) Islands', 'CC',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Serbia & Montenegro', 'CS',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Christmas Island', 'CX',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Western Sahara', 'EH',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('European Community', 'EY',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('France, Metropolitan', 'FX',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('South Georgia and the South Sandwich Islands', 'GS',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Heard Island and McDonald Islands', 'HM',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Norfolk Island', 'NF',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Saint Pierre and Miquelon', 'PM',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Occupied Palestinian Territory', 'PS',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Svalbard and Jan Mayen Islands', 'SJ',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('former USSR', 'SU',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Tokelau', 'TK',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('United States Minor Outlying Islands', 'UM',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Yugoslavia', 'YU',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Caribbean', 'XC',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('European Community', 'XE',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Africa', 'XF',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('South America', 'XM',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Asia', 'XS',true)"
execute "INSERT INTO trading_countries (name,iso_country_code,exclude_from_selection) VALUES ('Unknown', 'XX',true)"
    
  end

  def self.down
    TradingCountry.delete_all
  end
end
